site_name: text-kgc-data
site_description: Library and command-line utility for rendering projects templates.
site_url: https://tj-coding.gitlab.io/{{project_name_kebab_cased}}
repo_url: https://gitlab.com/TJ-coding/{{project_name_kebab_cased}}
repo_name: tj-coding/{{project_name_kebab_cased}}
watch: [../text_kgc_data_proj]
edit_uri_template: 'edit/master/Document/docs/{path}?plain=1'
nav:
  - Overview: "index.md"
  - Standardised File Format: "standardised_tkg.md"
  - WN18RR Example: "wn18rr_example.md"
  - Wikidata5m Example: "wikidata5m_example.md"
  
theme:
  name: material
  features:
    - content.code.annotate
    - navigation.top
    - navigation.tracking
    - content.action.edit
    - content.action.view
  palette:
    - media: "(prefers-color-scheme)"
      toggle:
        icon: material/brightness-auto
        name: Switch to light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: grey
      accent: amber
      toggle:
        icon: material/weather-sunny
        name: Switch to dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: indigo
      accent: orange
      toggle:
        icon: material/weather-night
        name: Switch to system preference
  icon:
    tag:
      labbook: octicons/beaker-24
      strategic-plan: material/strategy
    repo: fontawesome/brands/gitlab


extra:
  tags:
    Labbook: labbook
    Strategic Plan: strategic-plan

extra_css:
  - css/mkdocstrings.css
  - stylesheets/windows.css

markdown_extensions:
  - admonition
  - pymdownx.highlight:
      use_pygments: true
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
        - name: plotly
          class: mkdocs-plotly
          format: !!python/name:mkdocs_plotly_plugin.fences.fence_plotly
  - pymdownx.emoji
  - pymdownx.magiclink
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.details
  - toc:
      permalink: true
  - footnotes
  - attr_list
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - pymdownx.snippets
  - abbr
  - md_in_html
  - def_list
  - pymdownx.tasklist:
      custom_checkbox: true

  
plugins:
  - autorefs
  - search
  - markdown-exec
  - blog
  - plotly
  - tags
  - mkdocstrings:
      default_handler: python
      handlers:
        python:
          paths: [../text_kgc_data_proj]
          options:
            show_if_no_docstring: true
            show_signature_annotations: true
  - literate-nav:
      nav_file: SUMMARY.md